### ISSUE TITLE
the repo name is joy-v1, but it is listed everywhere as joi-v1

### ISSUE THREAD

**Issue by nwoetzel** [palmerabollo/joi-v1#1]
https://www.npmjs.com/package/joi-v1
https://libraries.io/npm/joi-v1

This seems to mess up some dependencies (I am trying to install npm less using https://github.com/francoispluchino/composer-asset-plugin) and at some point it tries to read from https://github.com/palmerabollo/joi-v1

**Comment by palmerabollo** [comment]
I'm looking into it. The module "joy-v1" should be public.

**Comment by palmerabollo** [comment]
My fault. Renamed to joi-v1 in github. The npm module is all right.

**Comment by nwoetzel** [comment]
Thanks for fixing that.
It really only was a problem when pulling from this repo instead of using the module repos. (This is what https://github.com/francoispluchino/composer-asset-plugin does)

The Readme.md has a last reference to 'joy' instead of 'joi' - no big deal though
